# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dfhtrbm_c <- function(t, x0, nu, kappa, sigma) {
    .Call(`_refbrown_dfhtrbm_c`, t, x0, nu, kappa, sigma)
}

pfhtrbm_c <- function(t, x0, nu, kappa, sigma) {
    .Call(`_refbrown_pfhtrbm_c`, t, x0, nu, kappa, sigma)
}

solveQuad <- function(slope, intercept, t_start, u) {
    .Call(`_refbrown_solveQuad`, slope, intercept, t_start, u)
}

rfhtrbm_c <- function(n, x0, nu, kappa, sigma, k, lambda_1, t_point, slopes, intercepts, M, I, pt_point) {
    .Call(`_refbrown_rfhtrbm_c`, n, x0, nu, kappa, sigma, k, lambda_1, t_point, slopes, intercepts, M, I, pt_point)
}

pfhtrbm_c_db <- function(t, x0, nu, kappa, sigma) {
    .Call(`_refbrown_pfhtrbm_c_db`, t, x0, nu, kappa, sigma)
}

lklhSubj <- function(t, event, x0, nu, kappa, sigma) {
    .Call(`_refbrown_lklhSubj`, t, event, x0, nu, kappa, sigma)
}

obsLklh_c <- function(t, event, covar_sigma, covar_kappa, mcmc_sigma, mcmc_kappa, mcmc_gamma, mcmc_theta, mc_z1, mc_z2, frailty, x0, nu) {
    .Call(`_refbrown_obsLklh_c`, t, event, covar_sigma, covar_kappa, mcmc_sigma, mcmc_kappa, mcmc_gamma, mcmc_theta, mc_z1, mc_z2, frailty, x0, nu)
}

simPath_c <- function(x0, nu, kappa, sigma, dt) {
    .Call(`_refbrown_simPath_c`, x0, nu, kappa, sigma, dt)
}

