##
## R package reThReg by Yingfa Xie and Jun Yan
## Copyright (C) 2022
##
## This file is part of the R package reThReg.
##
## The R package reThReg is free software: You can redistribute it and/or
## modify it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or any later
## version (at your option). See the GNU General Public License at
## <https://www.gnu.org/licenses/> for details.
##
## The R package reThReg is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
##

# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dFHT_c <- function(t, x0, nu, kappa, sigma) {
    .Call(`_reThReg_dFHT_c`, t, x0, nu, kappa, sigma)
}

pFHT_c <- function(t, x0, nu, kappa, sigma) {
    .Call(`_reThReg_pFHT_c`, t, x0, nu, kappa, sigma)
}

solveQuad <- function(slope, intercept, t_start, u) {
    .Call(`_reThReg_solveQuad`, slope, intercept, t_start, u)
}

rFHT_c <- function(n, x0, nu, kappa, sigma, k, lambda_1, t_point, slopes,
                   intercepts, M, I, pt_point) {
    .Call(`_reThReg_rFHT_c`, n, x0, nu, kappa, sigma, k, lambda_1, t_point,
          slopes, intercepts, M, I, pt_point)
}

