##
## R package refbrown by Author and Author
## Copyright (C) 2022
##
## This file is part of the R package refbrown.
##
## The R package refbrown is free software: You can redistribute it and/or
## modify it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or any later
## version (at your option). See the GNU General Public License at
## <https://www.gnu.org/licenses/> for details.
##
## The R package refbrown is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
##

# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dfhtrbm_c <- function(t, x0, nu, kappa, sigma) {
    .Call(`_refbrown_dfhtrbm_c`, t, x0, nu, kappa, sigma)
}

pfhtrbm_c <- function(t, x0, nu, kappa, sigma) {
    .Call(`_refbrown_pfhtrbm_c`, t, x0, nu, kappa, sigma)
}

solveQuad <- function(slope, intercept, t_start, u) {
    .Call(`_refbrown_solveQuad`, slope, intercept, t_start, u)
}

rfhtrbm_c <- function(n, x0, nu, kappa, sigma, k, lambda_1, t_point, slopes, intercepts, M, I, pt_point) {
    .Call(`_refbrown_rfhtrbm_c`, n, x0, nu, kappa, sigma, k, lambda_1, t_point, slopes, intercepts, M, I, pt_point)
}

simPath_c <- function(x0, nu, kappa, sigma, dt) {
    .Call(`_refbrown_simPath_c`, x0, nu, kappa, sigma, dt)
}

